### ISSUE TITLE
`ASCAD_generate.py` script for new dataset

### ISSUE THREAD

**Issue by SpikingNeuron** [ANSSI-FR/ASCAD#11]
Hey good to see that the dataset is now available for random key.
But I do not see the updated script for ASCAD_generate.py.
It is still having old information and the link for new script as given in documentation [here](https://github.com/ANSSI-FR/ASCAD/tree/master/ATMEGA_AES_v1/ATM_AES_v1_variable_key#the-ascad-databases) is broken.

```
profiling_index = [n for n in range(0, 50000)]
attack_index = [n for n in range(50000, 60000)]
target_points=[n for n in range(45400, 46100)]
```
 
Shouldn't that be
```
profiling_index = [n for n in range(0, 100000)]
attack_index = [n for n in range(100000, 150000)]
target_points=[n for n in range(45400, 46100)]
```

Also, can you point me to publication or repo to check the accuracy numbers.
I can use the trained model provided by you but it would be helpful to put the numbers in readme.md.

**Comment by prouff** [comment]
Indeed, the default values in the ASCAD_generate.py script have not been changed. To use the script for the new dataset, we propose in our README to launch the script with a link to a file describing the parameters (you can use the file example_generate_params given in the repo ASCAD/ATMEGA_AES_v1/ATM_AES_v1_variable_key/).

We will add some elements about the accuracy obtained with the new model and the new dataset.

**Comment by SpikingNeuron** [comment]
Hey thanks, Emmanuel ... it was easy to figure out how to use the parameters file... 
Apart from that, it would be nice if you share some metrics on new dataset in the repo .... it will be really helpful
