### ISSUE TITLE
Cannot break other subkeys.

### ISSUE THREAD

**Issue by Xuyang-Huang** [ANSSI-FR/ASCAD#17]
It seems like cannot break other subkeys, even retrain new models for each subkey  : (
but I'm not sure weather it is my problem.

**Comment by rstrullu** [comment]
Hi,

Thank you for your interest in ASCAD. It seems that we need more information to help you about your problem. Do you use the ASCAD ATMEGA datasets? In this case you need to extract the correct points of interest from the raw datasets. Our attacks were designed for targeting the third byte of the key. If you want to target an other key byte, you need to select the points of the traces that correspond to the leakage with a SNR and extract the raw trace with the ASCAD_generate_script. If you use the ASCAD STM32 dataset, then our default attack targets all the key bytes at the same time.

Regards,
ASCAD Team

**Comment by Xuyang-Huang** [comment]
Thanks for your reply.

Yes, after finding the interval of interest with SNR, all the subkeys can be broken.

Thanks again!
