### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by NEswariDevi** [ANSSI-FR/ASCAD#19]
From the White paper, it is found that tracepoints are selected from the interval [45400...46100] out of 1Lakh points. So, how it is possible to point out that these 700 points only correspond to the output of the third sbox operating in the first round of the encryption?

**Comment by rb-anssi** [comment]
This is pointed out using SNR leakage characterization. Please refer to the article https://eprint.iacr.org/2018/053.pdf, and particularly the SNR figures (Figure 2 and 3) to see how the window of interest has been selected.

Regrads,
