### ISSUE TITLE
Clock frequency of the target

### ISSUE THREAD

**Issue by LarsTeh** [ANSSI-FR/ASCAD#2]
Could you give any information on the clock frequency of the target implementation? From the documentation, I was only to figure out you are using an external clock, but not at which frequency you run it. Thank you very much!

**Comment by rb-anssi** [comment]
Hi LarsTeh,

You are absolutely right about the external clocking of the target. We have used a smartcard reader with a 4 MHz clock during our acquisitions (this is a standard frequency for ISO7816).

Regards,

**Comment by prouff** [comment]
Et bah ça c'est de la réactivité :-)

Bon we

Emmanuel


Le vendredi 29 juin 2018, Ryad Benadjila <notifications@github.com> a
écrit :

**Comment by LarsTeh** [comment]
Thank you very much for the quick response! :)
