### ISSUE TITLE
Trace Points

### ISSUE THREAD

**Issue by NEswariDevi** [ANSSI-FR/ASCAD#20]
https://github.com/ANSSI-FR/ASCAD/blob/410b92bab3bc69502b43c5cc9ccdec74794870be/ASCAD_generate.py#L382

How the trace points are selected? How the tracepoints must be selected and extracted for training and retrieving other bytes (from other rounds of SBOX) than the 3rd byte in first round of Sbox

**Comment by rb-anssi** [comment]
Please read the article https://eprint.iacr.org/2018/053.pdf and SNR leakage characterization to see how this timing window targeting the 3rd byte in first round Sbox has been selected. Other points of interest could be used, but we choose to focus on this one in our work.

Regards,

**Comment by peter-jp** [comment]
Ok, does the one lakh dataset collected correspond to only the first round or complete one encryption operation? 

This was wrt section 2.5.2 it was stated that the temporal acquisition window was set to record the first round of AES only.

I am asking this just for confirming my understanding. I have also plotted one of the traces from the Fixed dataset for better understanding.

![Fixed key_old_oneL_tracepoints_ATMEGA](https://user-images.githubusercontent.com/70361953/159217021-06210239-d310-4784-8149-080bb928ff0d.png)
?
