### ISSUE TITLE
how to implement SNR analysis?

### ISSUE THREAD

**Issue by kouyss** [ANSSI-FR/ASCAD#4]
in your paper, figure 2,3 shows the various intermediate values related to the processing of sbox(p[3] xor k[3]) in the interval [45400..46100], that was brilliant, would you mind introduce how to commit the SNR calculation betweent  sbox(p[3] xor k[3]) and the time samples ? i am going to reproduce this result for a further study, thank you.

**Comment by prouff** [comment]
Hi,
Footnote 7  in the paper does not respond to your question?

**Comment by kouyss** [comment]
I've calculated the Pearson correlation coefficient between the Lt and Z, but i don't know how to calculate the expected value E[Lt|Z] or the variance Var[Lt|Z], would you mind explain the equation(Var[ _E[Lt | Z] ]/E[ Var[Lt | Z]]_ ) more specifically?

**Comment by prouff** [comment]
Essentially, to compute E[Lt|Z]  or V[Lt|Z] you simply need to classify the traces L according to their respected value of Z. In other terms, for every trace/plaintext/key triplet $(l,p,k)$, you compute $z=f(p,k)$ (where eg $f$ is the AES Sbox) and you put $l$ in the set $E_z$. When you have done that for all the triplets, you compute for each E_z and every sample timing t the instantaneous mean and instantaneous variance of all the traces in this set.

**Comment by kouyss** [comment]
Thank you for your patience, would you mind attaching the SNR code in the github?

**Comment by prouff** [comment]
Please find here-after the SNR processing script that we used:
[ASCAD_SNR_processing.zip](https://github.com/ANSSI-FR/ASCAD/files/2329057/ASCAD_SNR_processing.zip)

**Comment by kouyss** [comment]
this will be a great help, thank you.

**Comment by kouyss** [comment]
hi @prouff , I have encountered several problems during the learning process.

1. the SNR code you provided describing the snr4 as _id_label_withMaskR = Sbox[k^p]^r_, _r = data['masks'][:,targeted_sbox_index-2]_, this is contradictory to your description in your paper where r[3] was used for snr4, snr5.

2. In your paper, Algorithm 1 contains 18-byte mask vector, this is contradictory to your ASCAD database where database['metadata']['masks'] only have 16-byte mask, I must have misunderstood this question. Can you explain what Rin and Rout means?

**Comment by prouff** [comment]
Hi,
1. As explained in the beginning of sections 2.5.1 and 2.6.1 of our ASCAD paper, the masks r[0] and r[1] have been set to zero and hence, for convenience, we did not put them into the masks arrays. For this reason, each masks array data[i,'masks'] exactly contains the masks r[2], r[3], ..., r[15] followed by rin and rout.  
2. Indeed, Algorithm 1 corresponds to the full description of the masked implementation where the masks r[0] and r[1] are not necessarily set to 0.

**Comment by kouyss** [comment]
Thank you very much for your answer, this is very helpful.

**Comment by kouyss** [comment]
Would you mind  explaining in detail the SNR processing in your code? Why does this represent SNR processing?  
varMean/MeanVar
Can you give me some quotes? Because the footnote 7 is not detailed enough.
Thank you.

**Comment by prouff** [comment]
Maybe you can read e.g. https://eprint.iacr.org/2014/1020.pdf
