### ISSUE TITLE
default value in the ASCAD_generate.py script

### ISSUE THREAD

**Issue by damrob** [ANSSI-FR/ASCAD#7]
Hi,

I have a remark concerning the ASCAD_generate.py script.

I have noticed that the default behavior of the script is to generate a set of Profiling traces without de-synchronization for ASCAD_desync50.h5 and ASCAD_desync100.h5 while the Attack traces are de-synchronized.

The following lines are from the script:

extract_traces(original_raw_traces_file, ascad_databases_folder + "ASCAD.h5")
extract_traces(original_raw_traces_file, ascad_databases_folder + "ASCAD_desync50.h5", attack_desync = 50)
extract_traces(original_raw_traces_file, ascad_databases_folder + "ASCAD_desync100.h5", attack_desync = 100)

For the two last line, the parameter profiling_desync is left to its default value i.e. 0.

Is this normal behavior?

**Comment by rb-anssi** [comment]
Hi,

The default value is indeed the normal behavior, and it is an arbitrary choice that we made to perform the training on synchronized traces and perform the attack on desychronized ones. This tends to show the ability of CNNs to be relatively resilient to desynchronization.

Performing the training on descynchronized traces should provide similar results though.

Regards,
